### ISSUE TITLE
Tree scaling working erratically

### ISSUE THREAD

**Issue by tferr** [morphonets/SNT#2]
Noticed by @carshadi:
Currently tree scaling [Tree#scale(xScale, yScale, zScale)] is flaky:
![image](https://user-images.githubusercontent.com/2439948/73416671-a024d800-42e3-11ea-82ae-d2e7a39a1da9.png)
orange:  Tree.scale(0.3, 0.3, 0.9)   |   blue: Tree.scale(0.9, 0.9, 0.9)   |   green: Tree.scale(1.2, 1.2, 1.2). The scaling bug behaves differently depending on the amount scaled by. Notice how the bizarre connected lines occur in different places in each.

**If the issue occurs only after saving the file**: 
I think culprit is likely original code from Simple Neurite Tracer that we never refactored. Namely this [chunk](https://github.com/morphonets/SNT/blob/2600779a592408989b414a947a01f89b94808455/src/main/java/sc/fiji/snt/PathAndFillManager.java#L713-L730). In more detail: All SWC export operations go through `PathAndFillManager#getSWCFor(Collection<Path> paths)`. There, the parent/child relationships are retrieved by finding the SWC point on the parent that is nearest to the child node. This is not only clumsy, is also unnecessary burden. A way to test this would be assess if the issue occurs only after saving the file (BTW, I'm assuming saving as TRACES, would not be affected by this) 

Loose list of relevant tasks:
 - [x] Assess if indeed the issue only occurs after saving the file
 - [ ] Change parsing so we no longer rely on "nearest index" computation 
 - [x] Reinstate [JUnit test ](https://github.com/morphonets/SNT/commit/0e2f43a1eab550bec8357368b3f4b20c0d22a2b4#diff-0372df108250561c0d9dad8f61ae9954L80-R80)  once issue is solved.

**Comment by tferr** [comment]
@carshadi, I think  f16f445 should fix this. Could you please confirm on your end?

**Comment by carshadi** [comment]
@tferr I'm using the Fiji script editor to test this (which I've just figured out is a bad idea).
If I run the following script multiple times, the output alternates between stating the scaling was successful and stating that the scaled tree contains multiple roots, leading to failure when trying to rebuild the graph after scaling. Additionally, if you un-comment the second TreeAnalyzer constructor after the scaling, the results for Strahler number are incorrect (reduced by 1) (maybe an issue with TreeAnalyzer?). I'm assuming the first constructed TreeAnalyzer only holds a reference to the tree, so that scaling the tree and getting new metrics from the same analyzer will reflect the scaling (which seems to be the case). In any case, I'll update the actual unit test with these metrics and see if the inconsistency in the output persists.

Also, as we discussed i'll implement the scaling method for DirectedWeightedGraph. It is going to be necessary to update the edge weights when scaling. How do you think we should go about that? Perform the edge weight update in the scaling method itself or as an additional member of DirectedWeightedGraph that could be applied in any scenario where the vertex coordinates are altered? 
```
# @Context context
# @SNTService snt

from sc.fiji.snt import Tree
from sc.fiji.snt.analysis import TreeAnalyzer

tree = Tree(r'C:\Users\cam\Desktop\SNT-morphonets\OP_1_auto-sigma-0.9-.swc')
analyzer = TreeAnalyzer(tree)
graph = tree.getGraph()
roots = len([n for n in graph.vertexSet() if graph.inDegreeOf(n) == 0])
print(roots)
print(len(analyzer.getBranchPoints()))
print(analyzer.getCableLength())
print(analyzer.getNPaths())
print(analyzer.getStrahlerNumber())
print(len(analyzer.getTerminalBranches()))
print(len(analyzer.getTips()))

tree.scale(0.5,0.5,0.5)
print('#### After Scaling ####')

# analyzer = TreeAnalyzer(tree)
graph = tree.getGraph()
roots = len([n for n in graph.vertexSet() if graph.inDegreeOf(n) == 0])
print(roots)
print(len(analyzer.getBranchPoints()))
print(analyzer.getCableLength())
print(analyzer.getNPaths())
print(analyzer.getStrahlerNumber())
print(len(analyzer.getTerminalBranches()))
print(len(analyzer.getTips()))

snt.dispose()
```

**Comment by carshadi** [comment]
Additionally, in the scaling section of the current TreeAnalyzerTest, we test cable length as follows:
https://github.com/morphonets/SNT/blob/f16f4459be6f2b48f38b4563bbcb1e4c856e0cb6/src/test/java/sc/fiji/snt/TreeAnalyzerTest.java#L82

This has been failing on build each time for me likely due to the floating point computation. What level of precision should we be aiming for in the difference?

**Comment by carshadi** [comment]
@tferr The sc.fiji.snt.TreeAnalyzerTest exhibits the same inconsistent behavior as the above the script. After some investigation, I believe the cause is the parallelStream in the scaling method here https://github.com/morphonets/SNT/blob/f16f4459be6f2b48f38b4563bbcb1e4c856e0cb6/src/main/java/sc/fiji/snt/Tree.java#L476

Changing this to a regular stream allows the test to run successfully each time. This resolves the issue with TreeAnalyzer giving different results as well.

**Comment by tferr** [comment]
Nice catch! this is great! I think everything should be OK now?

> How do you think we should go about that? Perform the edge weight update in the scaling method itself or as an additional member of DirectedWeightedGraph that could be applied in any scenario where the vertex coordinates are altered?

I would say the latter. We'll be using more and more DirectedWeightedGraph, so it would more useful down the road.

**Comment by carshadi** [comment]
@tferr https://github.com/morphonets/SNT/commit/2652889ded66cdfeab9ab1a1590ae394d1183fb8 appears to have fixed this for me as well!
