### ISSUE TITLE
Installation via pyimagej?

### ISSUE THREAD

**Issue by cyrilcros** [morphonets/SNT#60]
**Describe the bug**
I can't seem to be able to install SNT via a Maven endpoint. I see a `failed to resolve version for sc.fiji.snt:3.2.14:jar:RELEASE`.

**To Reproduce**

```
import imagej
ij = imagej.init(['sc.fiji:fiji:2.2.0', 'sc.fiji.snt:3.2.14'])
```

**Expected behavior**
I get an installed and versioned install of SNT. I am not sure if it possible or not...

**Screenshots**
![notebook](https://user-images.githubusercontent.com/10993194/132068796-70a2a80d-7516-49aa-a384-f745fb535c0c.png)
![shell](https://user-images.githubusercontent.com/10993194/132068906-6f67299a-a984-4a58-8a7f-ef4b208f57d8.png)

**Comment by cyrilcros** [comment]
Well, I just realized that this should be `sc.fiji.snt:snt:3.2.14`... Will try that.

**Comment by cyrilcros** [comment]
Ok, so I don't see it in `https://maven.scijava.org/content/repositories/releases/sc/fiji/`. I am assuming it won't be possible to install it this way. Could you please consider adding it to the Maven repository?
I can still install it via the Fiji update CLI, but pyimagej seems easier for tracking versions....

**Comment by carshadi** [comment]
Hi @cyrilcros , currently it is only possible to initialize `pyimagej` with a local Fiji installation that is subscribed to the Neuroanatomy update site (at least we have not tested other ways of doing so recently). E.g.,
```python
import imagej
ij = imagej.init("/path/to/your/Fiji.app/", headless=False)
```
 There are detailed instructions on how to set up the jupyter environment with SNT [here](https://github.com/morphonets/SNT/tree/master/notebooks)

**Comment by cyrilcros** [comment]
Ok, that definitely works. I was just thinking about what would be the best way to install a specific version via CLI. I can do something like `cd Fiji.app/ && ./ImageJ-linux64 --update update Neuroanatomy` for now. I would just ask you to conisder adding it to Maven like it used to be (https://maven.scijava.org/content/repositories/releases/sc/fiji/Simple_Neurite_Tracer/3.1.9/), that's a jar / poml and digests to update per release...

**Comment by carshadi** [comment]
Hey @cyrilcros, try this 
```python
import imagej
ij = imagej.init(['sc.fiji:fiji', 'org.morphonets:SNT:3.2.9'], headless=False)
```
It sort of appears to work, although it will be an old release. I had actually not known this was possible. @tferr thoughts on what it would take to make `4.0.0` available this way?

**Comment by ctrueden** [comment]
@carshadi The reason 4.0.0 is not available from maven.scijava.org is because this repository is still configured to build with travis-ci.org, but travis-ci.org is no longer operational. We have migrated all the core libraries to GitHub Actions already. I would recommend that this repository be migrated to GitHub Actions as well. I am happy to help do that. If you add me as an admin to the morphonets organization temporarily, I can add the necessary secrets as environment variables, and then you can run `github-actionify.sh` from the scijava-scripts repository to migrate over.

**Comment by carshadi** [comment]
That sounds good to me, I think either @tferr or @kephale would need to add you, as they are the org. owners

**Comment by tferr** [comment]
Added you both as owners. @ctrueden, thanks for looking into it. Coincidently, I was only now looking into it, and noticed that all the other Fiji repos, migrated to GitHub Actions en masse a couple of months. Was about to ping you. If you could migrate us as well, that would be great!

**Comment by ctrueden** [comment]
@tferr Thanks, I added the secrets and pushed a commit switching to GitHub Actions. It might have issues due to the Jupyter notebooks, though. I won't have time to address the problems (by fixing `ci-build.sh` in scijava-scripts) until Monday; I hope that's OK. But once we iron that out, we can force-push the 4.0.0 tag so that the CI builds the 4.0.0 release (or simply release 4.0.1—whichever you prefer).

**Comment by tferr** [comment]
@ctrueden, thanks a lot! Perfectly fine. We could release 4.0.1. Looking at the [build log](https://github.com/morphonets/SNT/runs/3571586055), it seems that the errors are mostly associated with doclint when building javadocs? Turning off doclint would fix it? or is it something that  you do not recommend?

**Comment by ctrueden** [comment]
@tferr Yeah, you could either add `<doclint>none</doclint>` to your `<properties>` if you don't care about the quality of the generated javadocs, or else go through and fix all the errors that are actually at `error` level (rather than `warning`). The command I typically use to find these easily is `mvn javadoc:javadoc | grep error`.

**Comment by cyrilcros** [comment]
Thanks for looking into this and fixing the Maven release! I am closing this issue, I will use the 4.0.1 version as soon as it is out.

**Comment by tferr** [comment]
Just to mention, that thanks to @ctrueden, 4.0.1 was released, this _should_ now work as expected:

```
import imagej
ij = imagej.init(['sc.fiji:fiji:2.3.1', 'sc.fiji.snt:4.0.1'])
```
Currently, the [notebook instructions](https://github.com/morphonets/SNT/tree/master/notebooks#setup) only mention initialization from a local install, it would be nice to update them to mention this. @cyrilcros, would be great if you could help us update the READMEs.

**Comment by kephale** [comment]
It is worth double checking that it does work. I have run into a couple of cases where the pyimagej dependency resolution wasn't exactly the same as in a Fiji installation.

**Comment by cyrilcros** [comment]
I am happy to help, but @ctrueden mentioned some dependency resolutions issues like @kephale noticed https://github.com/fiji/fiji/issues/292#issuecomment-920427578
The relevant issues are https://github.com/imagej/pyimagej/issues/140 and https://github.com/scijava/scyjava/issues/32

**Comment by kephale** [comment]
If it is the same one that I mentioned before, then it is resolved in
scyjava now

**Comment by cyrilcros** [comment]
So, here is what I see:
- `ij = imagej.init(['sc.fiji:fiji:2.3.1'])` works
- `ij = imagej.init(['sc.fiji:fiji:2.3.1', 'sc.fiji.snt:4.0.1'])` doesn't work
- `ij = imagej.init(['sc.fiji:fiji:2.3.1', 'sc.fiji.snt:snt:4.0.1'])` doesn't work
- `ij = imagej.init(['sc.fiji:fiji:2.3.1', 'org.morphonets:SNT:4.0.1'])` that works fine
With the last line I can start the tutorial https://github.com/morphonets/SNT/blob/master/notebooks/1_overview.ipynb from the `In [2]` part, and get the `4.0.1` version as expected. Installing the environment is just done with `conda create -n pyimagej -c conda-forge pyimagej openjdk=8` following https://github.com/imagej/pyimagej.
I haven't tried the GUI yet this way, I am using Jupyter notebooks for now...

**Comment by ctrueden** [comment]
> `ij = imagej.init(['sc.fiji:fiji:2.3.1', 'org.morphonets:SNT:4.0.1'])`

:point_up: This is the correct invocation. The Maven coordinate for the new SNT is `org.morphonets:SNT`. I edited @tferr's post above to minimize future confusion.

I tested on my system, and it also works for me (jgo==1.0.2, scyjava==1.2.0, pyimagej==1.0.1).

However, just to shine a light on the remaining dependency resolution issue: this invocation ends up with `net.imagej:imagej:2.1.0`, not `net.imagej:imagej:2.3.0` as it should. @hinerm and I know what's wrong and how to fix it (the solution is to address imagej/pyimagej#140), but the work isn't done yet.

**Comment by carshadi** [comment]
@cyrilcros on starting the GUI from a notebook, doing this works on my machine
```python
import imagej

ij = imagej.init(['sc.fiji:fiji:2.3.1', 'org.morphonets:SNT:4.0.1'], headless=False)

from scyjava import jimport

SNTUtils = jimport('sc.fiji.snt.SNTUtils')
print("We are running SNT %s" % SNTUtils.VERSION)

SNTService = jimport('sc.fiji.snt.SNTService')

snt = SNTService()
snt.setContext(ij.getContext())

snt.initialize(True) # start UI without image
```

**Comment by carshadi** [comment]
I am seeing some strangeness with certain gui commands from the notebook, e.g., path color coding. It seems to just run the command with whatever the previous input was from your desktop Fiji install, instead of prompting for input with a dialog.

**Comment by cyrilcros** [comment]
@carshadi - on my end it's normal the GUI doesn't work, I wasn't super clear I am running in headless mode. I was using Jupyterhub to run an image from https://github.com/jupyter/docker-stacks and I have no X server or display. 
I use a separate desktop install to annotate axons and save traces...

**Comment by ctrueden** [comment]
@cardashi wrote:
> It seems to just run the command with whatever the previous input was from your desktop Fiji install

Yep, because each time you run a command, the last-used inputs get persisted to the SciJava preferences area, which is shared across all copies of Fiji running on your system. However, it's weird that you don't see a dialog pop up... did you remember to do `ij.ui().showUI()` before starting to do other stuff in your notebook cells? If not, then there will be no active UI. But in that case, I'm surprised it runs at all, since those inputs—even though they get restored from the last-saved values—don't count as "resolved" and thus shouldn't allow the execution to continue without popping a dialog or (in headless mode) simply failing to run with an error.

**Comment by carshadi** [comment]
thanks @ctrueden, that seems to have fixed it. updated snippet
```python
import imagej

ij = imagej.init(['sc.fiji:fiji:2.3.1', 'org.morphonets:SNT:4.0.1'], headless=False)
ij.ui().showUI()

from scyjava import jimport

SNTUtils = jimport('sc.fiji.snt.SNTUtils')
print("We are running SNT %s" % SNTUtils.VERSION)

SNTService = jimport('sc.fiji.snt.SNTService')
snt = ij.get(SNTService.class_)

snt.initialize(True) # start UI without image
```

**Comment by ctrueden** [comment]
As an aside: the method `initialize(boolean)` is confusing because the `Service` interface has a method `initialize()` with no arguments, which is called when the service is first instantiated and added to the SciJava context. Maybe it's too late now, but I would suggest to name this method something else, to avoid user confusion with the SciJava application container mechanism.

**Comment by carshadi** [comment]
that's a good point, maybe `snt.startApp()`? I'll defer to @tferr on that one

**Comment by tferr** [comment]
(15 days later :cry: )
these are valid points. @carshadi, agree let's deprecate the `initialize(boolean)` call, in favor of a `startApp()` or  equivalent. Unfortunately, I don't think we can remove it altogether. 

@ctrueden,
thanks for the correction. Our maven ID is `org.morphonets.snt`, but our java packages are defined under `sc.fiji.snt`, i always find it confusing, and inevitably end up mixing them when using pyimagej.
