### ISSUE TITLE
TracerThread not available in sc.fiji.snt.

### ISSUE THREAD

**Issue by mcib3d** [morphonets/SNT#70]
I am testing my minimal plugin to trace between two ROI, but it seems there is a discrepancy about the class _TracerThread_ between the jar within Fiji and the jar version 4.0.1 on mavenCentral, I can see it should be in the package tracing but on the jar for development it is in the package snt. Thanks.

**Comment by tferr** [comment]
Hi Thomas,

`tracing.TracerThread` comes from `Fiji.app/plugins/Simple_Neurite_Tracer-3.1.10.jar`. We keep this jar around just in case someone still relies on it, but it is really a deprecated class that ought to be removed. It should not be used for anything, as the code has been archived.

I think the problem is that we moved things around with version 4:
We have added (@carshadi  did all the work) several new searches to snt. Up to SNTv4 TracerThread used to reside in `sc.fiji.snt`, but there were so many additions that we had to create a dedicated subpackage, so now everything resides in [sc.fiji.snt.tracing](https://github.com/morphonets/SNT/tree/master/src/main/java/sc/fiji/snt/tracing), so TracerThread is now at
`sc.fiji.snt.tracingTracerThread`. That's what should be available from `Fiji.app/jars/SNT-4.0.1.jar` (the one available from maven) and it is the version to be used.

The fact that we adopted "tracing" for this package makes things even more confusing.

BTW, @carshadi  may have some pointers on the pros/cons on adopting the new search classes: E.g., there are now ways to handle noisy images more effectively

**Comment by carshadi** [comment]
Hey @mcib3d ,

Sorry about the API break, as @tferr mentioned the core `sc.fiji.snt` package became overwhelmed so we moved all the path-finding related algorithm and data structure classes to the dedicated `sc.fiji.snt.tracing` package. We are working on a notebook that will demonstrate how to use the low level API, in particular the effect different cost functions can have in different image conditions. 

The high-level tracing API available through the `SNT` plugin methods are still backwards compatible, and there have been additional options added that improve their utility and convenience. For example, we added a headless option to `SNT#autoTrace` and the ability to [set different cost functions](https://javadoc.scijava.org/SNT/sc/fiji/snt/SNT.html#setCostType-sc.fiji.snt.SNT.CostType-). The default settings for these high-level methods are equivalent to the default behavior in the pre-4.0 versions. To reproduce the old behavior of `TracerThread`, use `Reciprocal(0, stackMaxIntensity)` for the cost function and `Euclidean` for the heuristic.

If tracing over very large images, I would recommend using `MAP` as the [search image type](https://javadoc.scijava.org/SNT/sc/fiji/snt/SNT.SearchImageType.html) since it has a much lighter memory footprint (on average) than `ARRAY`, which allocates an array of the same x-y dimensions as the image for each image plane encountered during the search. `MAP` does not pre-allocate memory this way, instead doubling its capacity whenever it hits its load factor, see [MapSearchImage.java](https://github.com/morphonets/SNT/blob/master/src/main/java/sc/fiji/snt/tracing/image/MapSearchImage.java). Of course, the memory use could eventually surpass that of an array if enough nodes are explored, but that is unlikely to happen in practice as long as individual searches do not span huge portions of the image. We have managed to use `MapSearchImage` to auto-trace over datasets of size `32256 * 23040 * 12288`. `ARRAY` is maintained mostly for for legacy purposes.

Please let us know if you have any questions or suggestions, we realize the documentation is currently lacking regarding this change.
