### ISSUE TITLE
Re-structure "Make Primary" command

### ISSUE THREAD

**Issue by tferr** [morphonets/SNT#85]
Described here:
https://forum.image.sc/t/no-paths-match-the-center-criteria/61827/12

**Comment by carshadi** [comment]
@tferr I combed through this a bit, the command calls this https://github.com/morphonets/SNT/blob/244c30a15fede1a78db4b68cf78bf11a6e9ab866/src/main/java/sc/fiji/snt/PathManagerUI.java#L2268-L2274
Which in turn calls this 
https://github.com/morphonets/SNT/blob/3a7de713255bdb13ae66fd170c9cf1edc5379028/src/main/java/sc/fiji/snt/Path.java#L1185-L1192

There are a couple different things going on here:
1) `path.setIsPrimary(false)` has no effect since the method aborts if the argument is `false`. So any connected `Path`s with order 1 will remain "primary" as determined by `path.isPrimary()`. Originally, this method set a boolean `primary` flag as a `Path` field, but this flag was removed in preference of operating on `order` some years ago (see commit https://github.com/morphonets/SNT/commit/35da7cb68f4d386b2bc51db38733d32b44c1bdfa). It turns out that `path.unsetPrimaryForConnected(...)` is the only place in the code base where `path.setIsPrimary(false)` is used, everywhere else the argument is `true`, which basically has the same effect as calling `path.setOrder(1)`
https://github.com/morphonets/SNT/blob/3a7de713255bdb13ae66fd170c9cf1edc5379028/src/main/java/sc/fiji/snt/Path.java#L418-L420
2) Even if the above method worked as expected, it still wouldn't be correct since it does not change the underlying topology of the Tree. For instance, if the `order` field of a terminal path is set to `1`, methods that parse the `Path` hierarchy will produce nonsensical results since all child `Path`s are assumed to have the single path with `startJoins == null` as ancestor (i.e., all `startJoins` should lead back to the primary path). See https://github.com/morphonets/SNT/blob/3a7de713255bdb13ae66fd170c9cf1edc5379028/src/main/java/sc/fiji/snt/PathAndFillManager.java#L656-L679

Most likely this all broke when we changed everything to use `startJoins` as the single source of truth for Tree structure.

Given that, I think it would be easiest to just remove this command since the (intended) behavior can be achieved more flexibly with the "Set Active Node as Tree Root" edit mode option.

If that sounds good to you, I'll go ahead and remove it.

**Comment by tferr** [comment]
@carshadi  Agree fully!  Let's remove it!
Alternatively, one could keep it so that it callsl "Set Active Node as Tree Root" using the starting node of the selected path? Not sure if that would be considered a convenience feature or menu clutter. What do you think?

**Comment by carshadi** [comment]
That could also work. What if the selected path is terminal? Would guess that most people would expect the end point to be the new "soma". For internal branches, I guess either first or last would work, but it may not be obvious to the user which was picked?. 

The "Set Active Node as Tree Root" command is nice in that regard since there is no such ambiguity. The user will always know which point is root.

**Comment by tferr** [comment]
Agree! no real benefits. let's pull the plug.

**Comment by carshadi** [comment]
done in https://github.com/morphonets/SNT/commit/5b128d9d07aa319db3ac1a4353f003191e826e3c
